### PR TITLE
Fix encoding of P-384 public key

### PR DESCRIPTION
**Pull request by peacekeeper**
I think this should be the correct multicodec encoding of a P-384 key...

### CODE REVIEW

**Review by msporny — APPROVED** [review]
I have no easy way to check this value... would have to write code to decode the base58btc value and then check the multicodec header... do you want me to check that, @peacekeeper, or do you feel pretty comfortable with this value? 

I believe I did the encoding correctly the first time... it looks like we might be off by a byte?

In any case, I'm happy to just take your PR now and we'll have to confirm later via test suite.

Are you ok/confident enough to merge now, @peacekeeper ?

**Comment by peacekeeper** [comment]
I'm pretty sure my change is correct. Your base58-encoded value is in hex:

```
120001d8ebdd36bddf1615b5aa10044b79cf188586d905e0e45611c8adc62de3e93ffb53b52494eacfb9ea93dc9229a9b7c31294f7834881e7be604d54e8ea64752575
```

And my value is in hex:

```
8124d8ebdd36bddf1615b5aa10044b79cf188586d905e0e45611c8adc62de3e93ffb53b52494eacfb9ea93dc9229a9b7c31294f7834881e7be604d54e8ea64752575
```

So your prefix before the actual key bytes is `120001`, and my prefix is `8124`. According to the [multicodec table](https://github.com/multiformats/multicodec/blob/master/table.csv#L142), the code for "p384-pub" is `0x1201`, but I think that is encoded as a [varint](https://github.com/multiformats/unsigned-varint) and therefore becomes `0x8124`.

Maybe @clehner or @OR13 or someone else could also verify.

**Comment by OR13** [comment]
yes, our implementation could be wrong... but we currently have these formats:

https://did.key.transmute.industries/did:key:zDnaevgFAhv9AgwgF7LUmEHzKSPhmXiNLUShrAiSyHJtM945k

https://did.key.transmute.industries/did:key:z82LknFT9NnExdcxpFoMARYgBLP5vwniv75zWxQHoss3Md1xLj57YujHzKSxgYWMmDi92MH

**Comment by peacekeeper** [comment]
> https://did.key.transmute.industries/did:key:z82LknFT9NnExdcxpFoMARYgBLP5vwniv75zWxQHoss3Md1xLj57YujHzKSxgYWMmDi92MH

Yes this also seems to have the correct `0x8124` multicodec varint value. I think this confirms that my PR here is correct.

**Review by msporny — APPROVED** [review]

**Pull request merged**
